PI\Sweet4uBundle\Entity\Catalogue:
    type: entity
    table: catalogue
    indexes:
        id_rp:
            columns:
                - id_rp
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        pic:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        idRp:
            targetEntity: ResponsablePatissier
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_rp:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
