PI\Sweet4uBundle\Entity\Client:
    type: entity
    table: client
    indexes:
        id_p:
            columns:
                - id_p
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        idP:
            targetEntity: Personne
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_p:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
