PI\Sweet4uBundle\Entity\Patisserie:
    type: entity
    table: patisserie
    indexes:
        id_rp:
            columns:
                - id_rp
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        idRp:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: id_rp
        delegation:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        codePostal:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: code_postal
        x:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        'y':
            type: integer
            nullable: true
            unsigned: false
            comment: ''
    lifecycleCallbacks: {  }
