PI\Sweet4uBundle\Entity\Personne:
    type: entity
    table: personne
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        prenom:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        adresse:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        dateNaissance:
            type: date
            nullable: false
            comment: ''
            column: date_naissance
        cin:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        login:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        pwd:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
