<?php

namespace Proxies\__CG__\PI\Sweet4uBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patisserie extends \PI\Sweet4uBundle\Entity\Patisserie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'delegation', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'adresse', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'codePostal', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'x', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'y', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'idRp');
        }

        return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'delegation', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'adresse', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'codePostal', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'x', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'y', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Patisserie' . "\0" . 'idRp');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patisserie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDelegation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelegation', array());

        return parent::getDelegation();
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function getX()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', array());

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function getY()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', array());

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRp', array());

        return parent::getIdRp();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDelegation($delegation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelegation', array($delegation));

        return parent::setDelegation($delegation);
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function setX($x)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', array($x));

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function setY($y)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', array($y));

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRp(\PI\Sweet4uBundle\Entity\ResponsablePatissier $idRp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRp', array($idRp));

        return parent::setIdRp($idRp);
    }

}
