<?php

namespace Proxies\__CG__\PI\Sweet4uBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commande extends \PI\Sweet4uBundle\Entity\Commande implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'payement', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'validation', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'modeP', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'modeL', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'articles', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'prixTotal', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'idRp', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'idC');
        }

        return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'payement', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'validation', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'modeP', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'modeL', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'articles', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'prixTotal', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'idRp', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commande' . "\0" . 'idC');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commande $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getPayement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayement', array());

        return parent::getPayement();
    }

    /**
     * {@inheritDoc}
     */
    public function getValidation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidation', array());

        return parent::getValidation();
    }

    /**
     * {@inheritDoc}
     */
    public function getModeP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeP', array());

        return parent::getModeP();
    }

    /**
     * {@inheritDoc}
     */
    public function getModeL()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModeL', array());

        return parent::getModeL();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticles', array());

        return parent::getArticles();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixTotal', array());

        return parent::getPrixTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdRp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdRp', array());

        return parent::getIdRp();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdC', array());

        return parent::getIdC();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setPayement($payement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayement', array($payement));

        return parent::setPayement($payement);
    }

    /**
     * {@inheritDoc}
     */
    public function setValidation($validation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidation', array($validation));

        return parent::setValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function setModeP($modeP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeP', array($modeP));

        return parent::setModeP($modeP);
    }

    /**
     * {@inheritDoc}
     */
    public function setModeL($modeL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModeL', array($modeL));

        return parent::setModeL($modeL);
    }

    /**
     * {@inheritDoc}
     */
    public function setArticles($articles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticles', array($articles));

        return parent::setArticles($articles);
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixTotal($prixTotal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixTotal', array($prixTotal));

        return parent::setPrixTotal($prixTotal);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdRp(\PI\Sweet4uBundle\Entity\ResponsablePatissier $idRp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdRp', array($idRp));

        return parent::setIdRp($idRp);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdC(\PI\Sweet4uBundle\Entity\Client $idC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdC', array($idC));

        return parent::setIdC($idC);
    }

}
