<?php

namespace Proxies\__CG__\PI\Sweet4uBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reclamation extends \PI\Sweet4uBundle\Entity\Reclamation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'sujet', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'contenu', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'lu', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'idTo', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'idFrom');
        }

        return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'sujet', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'contenu', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'lu', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'idTo', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Reclamation' . "\0" . 'idFrom');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reclamation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSujet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSujet', array());

        return parent::getSujet();
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', array());

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function getLu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLu', array());

        return parent::getLu();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTo', array());

        return parent::getIdTo();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdFrom', array());

        return parent::getIdFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setSujet($sujet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSujet', array($sujet));

        return parent::setSujet($sujet);
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', array($contenu));

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function setLu($lu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLu', array($lu));

        return parent::setLu($lu);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTo(\PI\Sweet4uBundle\Entity\Personne $idTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTo', array($idTo));

        return parent::setIdTo($idTo);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdFrom(\PI\Sweet4uBundle\Entity\Personne $idFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdFrom', array($idFrom));

        return parent::setIdFrom($idFrom);
    }

}
