<?php

namespace Proxies\__CG__\PI\Sweet4uBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commentaire extends \PI\Sweet4uBundle\Entity\Commentaire implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'date', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'commentaire', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'signalement', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'visible', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'idArticle', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'idP');
        }

        return array('__isInitialized__', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'id', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'date', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'commentaire', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'signalement', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'visible', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'idArticle', '' . "\0" . 'PI\\Sweet4uBundle\\Entity\\Commentaire' . "\0" . 'idP');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commentaire $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', array());

        return parent::getCommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalement', array());

        return parent::getSignalement();
    }

    /**
     * {@inheritDoc}
     */
    public function getVisible()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisible', array());

        return parent::getVisible();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArticle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArticle', array());

        return parent::getIdArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function getIdP()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdP', array());

        return parent::getIdP();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', array($commentaire));

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function setSignalement($signalement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalement', array($signalement));

        return parent::setSignalement($signalement);
    }

    /**
     * {@inheritDoc}
     */
    public function setVisible($visible)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisible', array($visible));

        return parent::setVisible($visible);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArticle(\PI\Sweet4uBundle\Entity\Article $idArticle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArticle', array($idArticle));

        return parent::setIdArticle($idArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdP(\PI\Sweet4uBundle\Entity\Personne $idP)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdP', array($idP));

        return parent::setIdP($idP);
    }

}
